[package]
name = "upbeat"
version = "0.1.0"
authors = ["David Simon <david.mike.simon@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5"
itertools = "0.9.0"
nalgebra = "0.18.1"
maplit = "1.0.2"
midly = "0.4.0"
rodio = "0.11.0"
